name: emo_ai
description: "emo.ai --version 0.0.6"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # <--- 1. Tambahkan ini di dev_dependencies

flutter:
  uses-material-design: true
  assets:
    - assets/

# <--- 2. Tambahkan blok ini di paling bawah (SEJAJAR dengan kata flutter: di atas)
flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/app_icon.png"